### ISSUE TITLE
Design first version of PollBot's API

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/PollBot#1]
This is a proposal for the design of PollBot's API.
What I'm thinking is: 

- the smaller bots (#2, #3, #4, #5, #6) are resources: 
  - GET /archives/54.0beta => `{"status":"not found"}`
  - GET /advisories/54.0beta => ??? ... 
- Let's start / use an OAS2 spec for planning out the design?

**Comment by Natim** [comment]
For the first version, we need the following endpoints:

- [ ] ``GET /v1/`` → Display information about the current server (project_name, project_version, http_api_version, repository_url, documentation_url) Refs #10 
- [ ] ``GET /v1/firefox/{version}`` → Get back status about the 5 (#2, #3, #4, #5 and #6) status
- [ ] ``GET /v1/firefox/{version}/(archives|security|releasenotes|bedrock|product-details)`` → Get back a specific status
- [ ] ``GET /v1/__version__`` → Get back the version.json file Refs #10 
- [ ] ``GET /v1/__heartbeat__`` → Get back status about the related services the service relies on.
- [ ] ``GET /v1/__lbheartbeat__`` → Always return 200 if the service is running

**Comment by mostlygeek** [comment]
I think each of the checks #2 #3 #4 #5 #6 should be a separate resource that can be accessed individually. Depending on the release @mozilla/release-management might be interested in all or some of the checks. 

In mozilla/delivery-dashboard#1 I'll make a comment about this requirement.

**Comment by Natim** [comment]
> I think each of the checks #2 #3 #4 #5 #6 should be a separate resource that can be accessed individually.

Do you have a specific use case in mind for that? It means more requests to the server which is usually a bad idea especially for rendering the dashboard.

I would be in favor of having them all in the same endpoint for the current use cases we have and to implement a specific resource if we need it later.

**Comment by mostlygeek** [comment]
> Do you have a specific use case in mind for that? 

The use case: RELMAN can specify which checks they are interested in for a release. 

> It means more requests to the server which is usually a bad idea especially for rendering the dashboard.

I'm not concerned about too many requests. It'll be busy on release day but we can abate that with nginx microcaches. 

> I would be in favor of having them all in the same endpoint for the current use cases we have and to implement a specific resource if we need it later.

I support it if it's prudent. It's likely we will be adding more polling/checking tasks. Having a combined endpoint makes less sense the more checks we have. 

To provide a combined check,  the checks should be run in parallel to have a decent response time (<10s). That would mean more complex code.  I think we should have simple, procedural and synchronous python handlers.  Use `cache-control` and nginx caches to prevent stampeding.

**Comment by Natim** [comment]
> To provide a combined check, the checks should be run in parallel 

Yes that's exactly what is [currently implemented](https://github.com/mozilla/PollBot/blob/master/pollbot/views/release.py#L10).
